version: '3'
services:
  react:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    container_name: react_container
    tty: true
    volumes:
      - ./react-app:/app/react
      - ./static:/app/react/static
    command: sh -c "cd /app/react && bun install && bun run dev --host"
    ports:
      - 3000:3000
      - 5173:5173
  go:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: go_container
    env_file: .env
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./go-app:/app/go
      - ./static:/app/go/static
    command: sh -c "cd /app/go && air -c .air.toml"
  db:
    image: mysql:8.0
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/mysql_data:/var/lib/mysql
    links:
      - go
